apiVersion: v1
kind: Pod
metadata:
  name: nginx-demo
  namespace: test-project
spec:
  containers:
  - name: nginx
    image: portainertest.azurecr.io/nginx:test
    resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
    ports:
    - containerPort: 80
